# Generated by Django 4.1.2 on 2023-10-05 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0014_cart'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='items',
            new_name='order_items',
        ),
    ]
